name: Deploy to Deployment EC2 Server

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Deployment EC2
        env:
          EC2_HOST: ${{ secrets.DEPLOYMENT_EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Your deployment commands for deployment server here
            cd /path/to/deployment/app
            git pull origin deployment
            ./deploy_script.sh
          EOF
